ruby/store-before/config/routes.rb
Store::Application.routes.draw do
  root to: 'products#index'
  resources :products
  resources :searches
end

ruby/store-before/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

ruby/store-before/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  def self.search(keywords)
    products = order(:name)
    products = products.where("name like ?", "%#{keywords}%") if keywords.present?
    products
  end
end

ruby/store-before/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search(params[:search])
  end
end

ruby/store-before/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new 
    @search = Search.new
  end
end

ruby/store-before/app/helpers/products_helper.rb
module ProductsHelper
end

ruby/store-before/app/helpers/searches_helper.rb
module SearchesHelper
end

ruby/store-before/app/views/products/_product.html.erb
<div class="product">
  <h2><%= link_to product.name, product %></h2>
  <div class="details">
    <%= number_to_currency(product.price) %>
    <% if product.category %>
      | Category: <%= product.category.name %>
    <% end %>
  </div>
</div>

ruby/store-before/app/views/products/index.html.erb
<h1>Products</h1>

<%= form_tag products_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= button_tag "Search", name: nil %>
  </p>
<% end %>
<p><%= link_to "Advanced Search", new_search_path %></p>

<div id="products">
  <%= render @products %>
</div>